version: "3.9"
services:
  server:
    image: golang:latest
    volumes:
      - .:/go/src
    networks:
      - networking-example
    command: bash -c "cd src/networking-server && go run ."
  client:
    image: golang:latest
    depends_on:
      - server
    volumes:
      - .:/go/src
    networks:
      - networking-example
    command: bash -c "cd src/networking-client && go run . server"
networks:
  networking-example:
